Tests
mohashyne/24hour_doctor-back_end pull request #17
Opened 2023-11-10 20:47 UTC by Kidd254

In this pull request I:

- [ ] Added the necessary gems and installed the relevant dependencies for unit and integration tests
- [ ]  Added unit tests for reservations and doctors controllers
- [ ] Updated the Readme

2023-11-10 22:25 UTC, bohaz approved these changes
Complete. Nice job

2023-11-11 13:40 UTC, Meltrust requested changes
Hi @Kidd254,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Included tests are passing ✔️ 
-  The API is working ✔️ 
-  Good readme ✔️ 
-  Nice routes ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-11-11 13:40 UTC, Meltrust commented on README.md
>  # 📗 Table of Contents
- [ ] You have linter errors.  Kindly correct them:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/c4406db5-a25d-4a23-9d3b-e373137c5192)

2023-11-11 13:40 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] In `database.yml` The development database and also the test database have the same name:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/2685c6c7-fd2d-44e8-8376-f31da8e225c0)

This results in the test database not being created:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/a25dcc76-8434-410f-a755-0ca6761bc3dc)

## Solution

Kindly, make sure the test database name is different like:

```
24hours_Doctor
24hours_Doctor_test
```
Look:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/1b117847-ef76-4ca7-89fd-43931a66b6b0)

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/4fa7764d-e3d1-4869-8c09-844e4d7883ec)

2023-11-11 13:40 UTC, Meltrust commented on README.md
- [x]  On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/0d081238-d379-4ff7-9528-db6a866984a9)


## Tips and extra help

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

That way, your app will be well documented 💪

2023-11-11 13:40 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] Kindly, include in your instructions the required db commands that your users will need to run your backend app: ``rails db:create, rails db:migrate. 👍

2023-11-11 13:40 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] You have several Rubocop issues, but this one is special, I'll explain: 

In `users_controller.rb`:

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/ab8498c2-3fef-4397-83d6-59132a13d60b)

Rubocop is saying "omit the hash value":

![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/e3d5e5fb-8558-4af3-af96-c2de9a18eab2)

This is because writing

```
@user = User.find_by(email: email)
```

...is the same as writing:

```
@user = User.find_by(email: )
```

This is a recent Ruby feature that has become a convention, and that's why Rubocop is enforcing it. 👍

2023-11-11 13:40 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] Kindly, implement on your readme a section called "tests" and include specific instructions about how to run them. 👍

2023-11-13 20:01 UTC, Kidd254 commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
Fixed

2023-11-14 05:26 UTC, Meltrust requested changes
Hi @Kidd254,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  API is working well✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-11-14 05:26 UTC, Meltrust commented on README.md
>  This project is licensed under the MIT License - you can click here to have more details [MIT](MIT.md).
- [ ] The license link is broken:


![image](https://github.com/mohashyne/24hour_doctor-back_end/assets/57421823/f0ef53bc-09cb-4ea3-bebc-92457effd430)

Kindly fix it. 👍

2023-11-14 05:26 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] Kindly, include in your instructions the required db commands that your users will need to run your backend app: ``rails db:create, rails db:migrate. 👍

2023-11-14 05:26 UTC, Meltrust commented on README.md
> +- [📖 24hours\Doctor_back_end ](#-24hours_doctor_back_end-)
- [ ] Kindly, implement on your readme a section called "tests" and include specific instructions about how to run them. 👍

2023-11-14 09:15 UTC, Meltrust approved these changes
#### Hi @Kidd254,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)




Cheers and Happy coding!👏👏👏


------

2023-11-14 09:25 UTC, merged